<?

$_data['issue'] = '27';

$_data['preloadImgs'] = 'img/i27-bg-guide.jpg,img/i27-bg-overlay-guide.png';

$_data['coverDisplay'] = false;

$_data['mainClass'] = 'i27-guide';

$_data['left'] = 'issue27/guide';

$_data['leftHtml'] = '"Guide"<strong>We break the Omerta</strong><span>The Season\'s Plot</span>';

$_data['right'] = 'issue27/cast';

$_data['rightHtml'] = '"Cast"<strong>Friends of mine, Friends of ours&hellip;</strong><span>Introducing the Crew</span>';

$_data['main'] =
	'<h3 class="page-title">In all Details</h3>'
	.'<h4 class="page-subtitle">Complete Episode Guide</h4>'
	.'<div class="sec-containers">'
		.'<h5 class="page-sectitle" data-sec="s1">Season 1</h5>'
		.'<h5 class="page-sectitle" data-sec="s2">Season 2</h5>'
		.'<h5 class="page-sectitle" data-sec="s3">Season 3</h5>'
		.'<div style="clear:both;"></div>'
		.'<h5 class="page-sectitle" data-sec="s4">Season 4</h5>'
		.'<h5 class="page-sectitle" data-sec="s5">Season 5</h5>'
		.'<h5 class="page-sectitle" data-sec="s6">Season 6</h5>'
		.'<div class="info">'
			.'Select an episode to display its plot&hellip;<br/>'
		.'</div>'
		.'<div class="sec-container s1">'
			.'<div class="guide">'
				.'<dl class="head">'
					.'<dd class="number">No.</dd>'
					.'<dd class="number season"></dd>'
					.'<dd class="title">Title</dd>'
					.'<dd class="director">Director</dd>'
					.'<dd class="writer">Writer</dd>'
					.'<dd class="date">Air date</dd>'
					.'<dt></dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">1</dd>'
					.'<dd class="number season">1</dd>'
					.'<dd class="title">"The Sopranos"</dd>'
					.'<dd class="director">David Chase</dd>'
					.'<dd class="writer">David Chase</dd>'
					.'<dd class="date">January 10, 1999</dd>'
					.'<dt>Tony Soprano, a capo in the DiMeo Crime Family, begins therapy with Dr. Jennifer Melfi after having anxiety attacks. His mother, Livia, refuses to move to a nursing home. Tony\'s Uncle Junior wants to use Tony\'s friend\'s restaurant as a location for a murder, but Tony prevents this by having the restaurant blown up. Christopher Moltisanti, Tony\'s nephew, murders the representative of a Czech mob that was trying to move in on the family waste management company.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">2</dd>'
					.'<dd class="number season">2</dd>'
					.'<dd class="title">"46 Long"</dd>'
					.'<dd class="director">Dan Attias</dd>'
					.'<dd class="writer">David Chase</dd>'
					.'<dd class="date">January 17, 1999</dd>'
					.'<dt>Christopher and Brendan Filone begin hijacking trucks. When they find that the owner of the trucks pays Junior for protection, their drug addictions prevent them from respecting Junior\'s orders to stop. Carmela asks Tony for a favor involving A.J.\'s science teacher\'s stolen car. After one too many accidents, Tony forces Livia to move into a nursing home against her will.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">3</dd>'
					.'<dd class="number season">3</dd>'
					.'<dd class="title">"Denial, Anger, Acceptance"</dd>'
					.'<dd class="director">Nick Gomez</dd>'
					.'<dd class="writer">Mark Saraceni</dd>'
					.'<dd class="date">January 24, 1999</dd>'
					.'<dt>The Sopranos hire the Buccos to cater a dinner party. Tony\'s daughter, Meadow, asks Christopher and Brendan for speed to help stay awake for SAT preparation. Tony accepts the task of securing a divorce for a Hasidic Jew\'s daughter. Junior unleashes retribution upon Christopher and Brendan for their truck hijackings.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">4</dd>'
					.'<dd class="number season">4</dd>'
					.'<dd class="title">"Meadowlands"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">Jason Cahill</dd>'
					.'<dd class="date">January 31, 1999</dd>'
					.'<dt>Tony has his friend Detective Vin Makazian follow Dr. Melfi after she appears in his dreams. Christopher calls for retaliation against Junior and Mikey Palmice for the death of Brendan. The question of who will be Jackie Aprile\'s successor arises.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">5</dd>'
					.'<dd class="number season">5</dd>'
					.'<dd class="title">"College"</dd>'
					.'<dd class="director">Allen Coulter</dd>'
					.'<dd class="writer">James Manos Jr., David Chase</dd>'
					.'<dd class="date">February 7, 1999</dd>'
					.'<dt>Tony and Meadow travel to Maine to visit colleges; and they discuss the nature of Tony\'s "business". Carmela fights the flu, and seeks comfort from Father Intintola after finding out that Tony\'s secret therapist is female. Tony comes across an old associate who has joined the Witness Protection Program and tracks him down for "business" purposes.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">6</dd>'
					.'<dd class="number season">6</dd>'
					.'<dd class="title">"Pax Soprana"</dd>'
					.'<dd class="director">Alan Taylor</dd>'
					.'<dd class="writer">Frank Renzulli</dd>'
					.'<dd class="date">February 14, 1999</dd>'
					.'<dt>Uncle Junior is appointed boss of the DiMeo crime family. Tony engineers a way to get Junior to extend some leniency to a close Jewish friend. Carmela and Tony\'s 18th anniversary dinner turns sour. The Prozac Dr. Melfi prescribes for Tony begins taking a negative toll on his libido, though his recurring dreams lead him to become attracted to her, and Junior Soprano becomes Boss.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">7</dd>'
					.'<dd class="number season">7</dd>'
					.'<dd class="title">"Down Neck"</dd>'
					.'<dd class="director">Lorraine Senna Ferrara</dd>'
					.'<dd class="writer">Robin Green & Mitchell Burgess</dd>'
					.'<dd class="date">February 21, 1999</dd>'
					.'<dt>A.J. and his friends steal some sacramental wine and arrive to gym class drunk. Tony thinks little of the incident, until the school psychologist informs him that his son may have ADHD. Tony reflects on his own childhood antics in therapy. A.J. is grounded and forced to regularly visit his grandmother, where he lets slip that Tony is in therapy.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">8</dd>'
					.'<dd class="number season">8</dd>'
					.'<dd class="title">"The Legend of Tennessee Moltisanti"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Frank Renzulli, David Chase</dd>'
					.'<dd class="date">February 28, 1999</dd>'
					.'<dt>The Lupertazzi Crime Family goes on the lam to avoid possible indictments from the FBI. Tony and his crew, though not including Christopher, are named as possible subjects in a grand jury investigation. Christopher is depressed by his exclusion; he has nightmares, and unsuccessfully tries to shift his focus by writing a screenplay. Livia learns of news that shocks her and passes the news to Junior.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">9</dd>'
					.'<dd class="number season">9</dd>'
					.'<dd class="title">"Boca"</dd>'
					.'<dd class="director">Andy Wolk</dd>'
					.'<dd class="writer">Jason Cahill, Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">March 7, 1999</dd>'
					.'<dt>Parents are shocked when a successful high school coach commits a terrible crime. Gossip reaches Tony regarding Junior\'s sexual secrets. Junior is humiliated when Tony makes open references to them, and Roberta.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">10</dd>'
					.'<dd class="number season">10</dd>'
					.'<dd class="title">"A Hit Is a Hit"</dd>'
					.'<dd class="director">Matthew Penn</dd>'
					.'<dd class="writer">Joe Bosso, Frank Renzulli</dd>'
					.'<dd class="date">March 14, 1999</dd>'
					.'<dt>According to the suggestions of Dr. Melfi and Carmela, Tony attempts to be more social by getting to know some of his neighbors better. Christopher and his girlfriend Adriana La Cerva befriend rap mogul Massive Genius. Christopher agrees to help Adriana produce a demo for a band, though one of its members is her ex-boyfriend. Massive Genius threatens to sue Hesh for supposedly stolen music royalties.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">11</dd>'
					.'<dd class="number season">11</dd>'
					.'<dd class="title">"Nobody Knows Anything"</dd>'
					.'<dd class="director">Henry J. Bronchtein</dd>'
					.'<dd class="writer">Frank Renzulli</dd>'
					.'<dd class="date">March 21, 1999</dd>'
					.'<dt>A tip from Vin Makazian leads Tony to make a tough decision regarding one of his most trusted friends. Tony has Paulie Walnuts keep an eye on things. Junior, Mikey and Chucky Signore, after conferring with Livia, conspire together to consolidate power.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">12</dd>'
					.'<dd class="number season">12</dd>'
					.'<dd class="title">"Isabella"</dd>'
					.'<dd class="director">Allen Coulter</dd>'
					.'<dd class="writer">Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">March 28, 1999</dd>'
					.'<dt>Despite prescriptions for Prozac and lithium from Dr. Melfi, Tony falls into chronic depression. He hallucinates meeting Isabella, a beautiful Italian exchange student staying at the Cusamanos\', which temporarily lifts his spirits. Junior\'s plan is put into action. The FBI pay a visit to the Sopranos.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">13</dd>'
					.'<dd class="number season">13</dd>'
					.'<dd class="title">"I Dream of Jeannie Cusamano"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">David Chase</dd>'
					.'<dd class="date">April 4, 1999</dd>'
					.'<dt>Junior agrees with Tony on the situation with Jimmy Altieri. Tony finds out about his mother and uncle\'s plot. He warns Dr. Melfi that her life may be in danger. Christopher, Paulie, and Silvio Dante take care of family business. Tony\'s friend Artie Bucco re-opens his restaurant.</dt>'
				.'</dl>'
				.'<div style="clear:both;"></div>'
			.'</div>'
		.'</div>'
		.'<div class="sec-container s2">'
			.'<div class="guide">'
				.'<dl class="head">'
					.'<dd class="number">No.</dd>'
					.'<dd class="number season"></dd>'
					.'<dd class="title">Title</dd>'
					.'<dd class="director">Director</dd>'
					.'<dd class="writer">Writer</dd>'
					.'<dd class="date">Air date</dd>'
					.'<dt></dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">14</dd>'
					.'<dd class="number season">1</dd>'
					.'<dd class="title">"Guy Walks Into a Psychiatrist\'s Office..."</dd>'
					.'<dd class="director">Allen Coulter</dd>'
					.'<dd class="writer">Jason Cahill</dd>'
					.'<dd class="date">January 16, 2000</dd>'
					.'<dt>Several months in the aftermath of season 1, Tony has assumed control of the DiMeo crime family. As suddenly as he vanished, Pussy returns. Junior is in prison and Livia is recovering from her stroke. Dr. Melfi has gone on the lam at Tony\'s request. Tony\'s sister Janice arrives to stay at Tony\'s house.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">15</dd>'
					.'<dd class="number season">2</dd>'
					.'<dd class="title">"Do Not Resuscitate"</dd>'
					.'<dd class="director">Martin Bruestle</dd>'
					.'<dd class="writer">Robin Green, Mitchell Burgess, Frank Renzulli</dd>'
					.'<dd class="date">January 23, 2000</dd>'
					.'<dt>Tony tries to settle a construction protest involving the former assets of Uncle Junior. Junior\'s lawyer manages to get him released from prison, though on house arrest. Pussy\'s true loyalties are revealed. Janice and Tony discuss the possibility of a DNR order for Livia.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">16</dd>'
					.'<dd class="number season">3</dd>'
					.'<dd class="title">"Toodle Fucking-Oo"</dd>'
					.'<dd class="director">Lee Tamahori</dd>'
					.'<dd class="writer">Frank Renzulli</dd>'
					.'<dd class="date">January 30, 2000</dd>'
					.'<dt>After a 10-year stint in prison, Richie Aprile, brother to the late Jackie Aprile, Sr., is released from jail and re-enters the family business. His lack of understanding of how things work since he went to prison causes friction between him and Tony. Meadow trashes her grandmother\'s house, and her subsequent punishment ignites a major argument between Carmela and Janice.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">17</dd>'
					.'<dd class="number season">4</dd>'
					.'<dd class="title">"Commendatori"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">David Chase</dd>'
					.'<dd class="date">February 6, 2000</dd>'
					.'<dt>Tony, Paulie, and Christopher take a business trip to Italy. Her husband gone, Carmela ponders the nature of their marriage. In Italy, Tony strikes a deal with his female counterpart. Angie Bonpensiero confides in Carmela that she wants a divorce from Pussy.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">18</dd>'
					.'<dd class="number season">5</dd>'
					.'<dd class="title">"Big Girls Don\'t Cry"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">February 13, 2000</dd>'
					.'<dt>As part of Tony\'s deal, Neapolitan enforcer Furio Giunta arrives in the U.S. as the newest addition to Tony\'s crew. Christopher enrolls in an "Acting for Screen Writers" class. Pussy shows open hostility to the new arrival. Dr. Melfi decides to resume therapy sessions with Tony.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">19</dd>'
					.'<dd class="number season">6</dd>'
					.'<dd class="title">"The Happy Wanderer"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">Frank Renzulli</dd>'
					.'<dd class="date">February 20, 2000</dd>'
					.'<dt>Tony discusses with Dr. Melfi people who make him "miserable". Sean Gismonte and Matthew Bevilaqua begin to work the "Executive Game" poker sessions (with Frank Sinatra Jr. in attendance). An old high school classmate of Tony\'s wants in on the "Executive Game". Janice makes an attempt to manipulate Richie.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">20</dd>'
					.'<dd class="number season">7</dd>'
					.'<dd class="title">"D-Girl"</dd>'
					.'<dd class="director">Allen Coulter</dd>'
					.'<dd class="writer">Todd A. Kessler</dd>'
					.'<dd class="date">February 27, 2000</dd>'
					.'<dt>A.J. presents an affront to his parents\' authority and refuses to be confirmed as a Catholic. Christopher develops romantic and professional involvements when resurrecting his interest in moviemaking. Pussy is pressured to wear a wire. Tony forces confirmation upon A.J. and, having learned that Christopher has written a screenplay, presents him with an ultimatum.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">21</dd>'
					.'<dd class="number season">8</dd>'
					.'<dd class="title">"Full Leather Jacket"</dd>'
					.'<dd class="director">Allen Coulter</dd>'
					.'<dd class="writer">Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">March 5, 2000</dd>'
					.'<dt>In regards to Meadow\'s upcoming college applications, Carmela looks to secure a favor from Jeannie Cusamano\'s sister, a Georgetown alumna. Richie tries to gain Tony\'s respect. Matthew and Sean formulate an ill-fated plan to win respect. Christopher\'s life is seriously threatened.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">22</dd>'
					.'<dd class="number season">9</dd>'
					.'<dd class="title">"From Where to Eternity"</dd>'
					.'<dd class="director">Henry J. Bronchtein</dd>'
					.'<dd class="writer">Michael Imperioli</dd>'
					.'<dd class="date">March 12, 2000</dd>'
					.'<dt>Christopher claims to witness a foreboding glimpse of the afterlife. Paulie grows worried that he is being haunted by those who he has killed. Tony seeks revenge, and brings Pussy along for the ride. Dr. Melfi finds trouble in coping with her disgust for Tony\'s "business".</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">23</dd>'
					.'<dd class="number season">10</dd>'
					.'<dd class="title">"Bust Out"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">Frank Renzulli, Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">March 19, 2000</dd>'
					.'<dt>Tony begins to panic when he learns of an eyewitness of a major crime. Pussy feeds the FBI false information. Richie, spurred by a manipulative Janice, tries to get Uncle Junior\'s support in finding a way to usurp Tony. Carmela shares an awkward moment with Scatino\'s brother in law.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">24</dd>'
					.'<dd class="number season">11</dd>'
					.'<dd class="title">"House Arrest"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">March 26, 2000</dd>'
					.'<dt>At the request of his lawyer, Tony spends time in his legitimate waste management career. Richie and Junior take risks to sustain a profitable cocaine network. Tony\'s health declines, as does the health of Dr. Melfi. Junior reunites with an old girlfriend while under house arrest.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">25</dd>'
					.'<dd class="number season">12</dd>'
					.'<dd class="title">"The Knight in White Satin Armor"</dd>'
					.'<dd class="director">Allen Coulter</dd>'
					.'<dd class="writer">Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">April 2, 2000</dd>'
					.'<dt>Richie continues his insubordination to Tony, though he is engaged to Janice. When Tony tries to break off his relationship with his comàre Irina, she attempts to commit suicide. A minor domestic dispute turns violent, though it provides Tony with a resolution to his problems with Richie and Janice.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">26</dd>'
					.'<dd class="number season">13</dd>'
					.'<dd class="title">"Funhouse"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">David Chase, Todd A. Kessler</dd>'
					.'<dd class="date">April 9, 2000</dd>'
					.'<dt>Tony gets food poisoning the day before Meadow\'s graduation; while trying to recover, his dreams lead him to resurrect old suspicions about an old friend. The FBI executes a search warrant, and arrests Tony.</dt>'
				.'</dl>'
				.'<div style="clear:both;"></div>'
			.'</div>'
		.'</div>'
		.'<div class="sec-container s3">'
			.'<div class="guide">'
				.'<dl class="head">'
					.'<dd class="number">No.</dd>'
					.'<dd class="number season"></dd>'
					.'<dd class="title">Title</dd>'
					.'<dd class="director">Director</dd>'
					.'<dd class="writer">Writer</dd>'
					.'<dd class="date">Air date</dd>'
					.'<dt></dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">27</dd>'
					.'<dd class="number season">1</dd>'
					.'<dd class="title">"Mr. Ruggerio\'s Neighborhood"</dd>'
					.'<dd class="director">Allen Coulter</dd>'
					.'<dd class="writer">David Chase</dd>'
					.'<dd class="date">March 4, 2001</dd>'
					.'<dt>Meadow enters college at Columbia University, A.J. continues to ignore authority, and Carmela starts taking tennis lessons. The FBI puts the Soprano residence under surveillance, but their plans are complicated when the house\'s plumbing ruptures. Patsy Parisi has revenge in mind over the death of his brother.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">28</dd>'
					.'<dd class="number season">2</dd>'
					.'<dd class="title">"Proshai, Livushka"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">David Chase</dd>'
					.'<dd class="date">March 4, 2001</dd>'
					.'<dt>Tony has an anxiety attack when he finds out that Meadow\'s new boyfriend, Noah Tannenbaum, is a Jewish African-American. The FBI wants Livia to testify against her son, but she dies before she can. Janice returns from Seattle to plan the funeral, and claim her inheritance.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">29</dd>'
					.'<dd class="number season">3</dd>'
					.'<dd class="title">"Fortunate Son"</dd>'
					.'<dd class="director">Henry J. Bronchtein</dd>'
					.'<dd class="writer">Todd A. Kessler</dd>'
					.'<dd class="date">March 11, 2001</dd>'
					.'<dt>Tony makes a major breakthrough with Dr. Melfi in attempting to ascertain the trigger of his anxiety attacks. Christopher becomes a made man, though he bungles his first assignment. A.J. excels on his freshman football team, but unexpectedly passes out at practice after becoming defensive captain.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">30</dd>'
					.'<dd class="number season">4</dd>'
					.'<dd class="title">"Employee of the Month"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">March 18, 2001</dd>'
					.'<dt>Dr. Melfi suggests that Tony bring Carmela to his sessions for a new perspective on his progress. Against Tony\'s orders, Ralph Cifaretto starts to introduce Jackie Aprile, Jr. to members of the family business. Dr. Melfi contemplates asking Tony for a favor.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">31</dd>'
					.'<dd class="number season">5</dd>'
					.'<dd class="title">"Another Toothpick"</dd>'
					.'<dd class="director">Jack Bender</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">March 25, 2001</dd>'
					.'<dt>Tony and Carmela\'s session with Dr. Melfi goes sour. Bobby Bacala, Sr. comes out of retirement to exact revenge on "Mustang Sally". Uncle Junior shares his cancer diagnosis with Tony. Meadow\'s relationship with her father is yet to improve, though she unknowingly does him a grand favor.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">32</dd>'
					.'<dd class="number season">6</dd>'
					.'<dd class="title">"University"</dd>'
					.'<dd class="director">Allen Coulter</dd>'
					.'<dd class="writer">Terence Winter, Salvatore J. Stabile</dd>'
					.'<dd class="date">April 1, 2001</dd>'
					.'<dt>A Bada Bing dancer involved with Ralph unexpectedly reaches out to Tony. Meadow\'s social life at college takes a sudden turn for the worse. Ralph\'s relationship with the Bada Bing dancer develops into a bad situation, and Tony interjects in a nonverbal manner.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">33</dd>'
					.'<dd class="number season">7</dd>'
					.'<dd class="title">"Second Opinion"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Lawrence Konner</dd>'
					.'<dd class="date">April 8, 2001</dd>'
					.'<dt>Uncle Junior survives surgery to remove his stomach cancer. The ongoing borrowing of money from Tony by Pussy\'s wife (widow, though unbeknownst to her) begins to run Tony\'s patience thin. Carmela considers making a large donation to Columbia University. Carmela receives some startling advice from a recommended colleague of Dr. Melfi. Tony becomes concerned with the quality of Junior\'s cancer treatment.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">34</dd>'
					.'<dd class="number season">8</dd>'
					.'<dd class="title">"He Is Risen"</dd>'
					.'<dd class="director">Allen Coulter</dd>'
					.'<dd class="writer">Robin Green, Mitchell Burgess, Todd A. Kessler</dd>'
					.'<dd class="date">April 15, 2001</dd>'
					.'<dt>Though Ralph feels that he is owed an apology, Tony instead bans him from Bada Bing. Meadow begins a serious relationship with Jackie Jr. Tony considers buying a new car. After another major disrespect, Tony disinvites Ralph, and Rosalie Aprile, to their Thanksgiving dinner.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">35</dd>'
					.'<dd class="number season">9</dd>'
					.'<dd class="title">"The Telltale Moozadell"</dd>'
					.'<dd class="director">Dan Attias</dd>'
					.'<dd class="writer">Michael Imperioli</dd>'
					.'<dd class="date">April 22, 2001</dd>'
					.'<dt>Though Tony and Rosalie are delighted, Carmela harbors reservations over the developing relationship between Meadow and Jackie Jr. Tony\'s latest extramarital relationship heats up. On Carmela\'s birthday, A.J. and friends vandalize school property, after which he is placed on probation. Christopher assumes ownership of a nightclub and makes a gift of the establishment to Adriana.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">36</dd>'
					.'<dd class="number season">10</dd>'
					.'<dd class="title">"...To Save Us All from Satan\'s Power"</dd>'
					.'<dd class="director">Jack Bender</dd>'
					.'<dd class="writer">Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">April 29, 2001</dd>'
					.'<dt>As Christmas looms near, Janice offers to cook the dinner. Tony comes across an old Santa Claus costume, prompting him to reminisce about Christmas 1995. Bobby Bacala is enlisted to play Santa Claus at Satriale\'s annual party. Jackie Jr. starts to walk down the wrong path, and Tony tries to set him straight.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">37</dd>'
					.'<dd class="number season">11</dd>'
					.'<dd class="title">"Pine Barrens"</dd>'
					.'<dd class="director">Steve Buscemi</dd>'
					.'<dd class="writer">Tim Van Patten, Terence Winter</dd>'
					.'<dd class="date">May 6, 2001</dd>'
					.'<dt>A standard collection goes horribly awry for Paulie and Christopher as they end up lost in the snowy Pine Barrens of South Jersey. Tony\'s relationship with Gloria starts to go south, as does that of Meadow and Jackie Jr.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">38</dd>'
					.'<dd class="number season">12</dd>'
					.'<dd class="title">"Amour Fou"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Frank Renzulli, David Chase</dd>'
					.'<dd class="date">May 13, 2001</dd>'
					.'<dt>Tony asks for advice on his relationship with Gloria from Dr. Melfi. Carmela and Gloria cross paths. With Meadow a thing of the past, Jackie Jr. and friends decide to take an ill-fated shot at earning some respect.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">39</dd>'
					.'<dd class="number season">13</dd>'
					.'<dd class="title">"Army of One"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">David Chase, Lawrence Konner</dd>'
					.'<dd class="date">May 20, 2001</dd>'
					.'<dt>Tony gives Ralph the responsibility of deciding the fate of Jackie Jr. A.J. is expelled, and his parents disagree over whether or not to send him to military school. Before he can be sent anywhere, it is discovered that A.J. inherited a distinctive trait from his father. Adriana makes a new friend with a hidden agenda.</dt>'
				.'</dl>'
				.'<div style="clear:both;"></div>'
			.'</div>'
		.'</div>'
		.'<div class="sec-container s4">'
			.'<div class="guide">'
				.'<dl class="head">'
					.'<dd class="number">No.</dd>'
					.'<dd class="number season"></dd>'
					.'<dd class="title">Title</dd>'
					.'<dd class="director">Director</dd>'
					.'<dd class="writer">Writer</dd>'
					.'<dd class="date">Air date</dd>'
					.'<dt></dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">40</dd>'
					.'<dd class="number season">1</dd>'
					.'<dd class="title">"For All Debts Public and Private"</dd>'
					.'<dd class="director">Allen Coulter</dd>'
					.'<dd class="writer">David Chase</dd>'
					.'<dd class="date">September 15, 2002</dd>'
					.'<dt>Tony lends Uncle Junior a helping hand as legal bills begin to pile up. Carmela wants to learn more about the family finances, though that is privileged information from Tony\'s point of view. Christopher gets information on the man who probably murdered his father. Adriana continues her "friendship" with an undercover FBI agent.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">41</dd>'
					.'<dd class="number season">2</dd>'
					.'<dd class="title">"No Show"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">Terence Winter and David Chase</dd>'
					.'<dd class="date">September 22, 2002</dd>'
					.'<dt>Resentment abounds when Christopher is made acting capo of Paulie\'s crew. Meadow slips into a depression, announcing that she will be dropping out of school and traveling to Europe. Adriana learns the truth about her new friend Danielle. Tony grows concerned when Janice and Ralph begin a serious relationship.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">42</dd>'
					.'<dd class="number season">3</dd>'
					.'<dd class="title">"Christopher"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Michael Imperioli, Maria Laurino</dd>'
					.'<dd class="date">September 29, 2002</dd>'
					.'<dt>Sixteen years are on the line when the trial of U.S. v. Corrado John Soprano (Uncle Junior) gets underway. Silvio, intensely proud of his heritage, takes a stand to break up a Native American protest against the annual Columbus Day parade. Bobby Bacala suffers an incredibly crippling loss. Ralph\'s general popularity continues to suffer.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">43</dd>'
					.'<dd class="number season">4</dd>'
					.'<dd class="title">"The Weight"</dd>'
					.'<dd class="director">Jack Bender</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">October 6, 2002</dd>'
					.'<dt>Johnny Sack remains furious at Ralph after learning of an off-color remark about Ginny\'s weight. Carmela finds herself becoming attracted to Furio, who holds a housewarming party. Tony worries that Meadow will abandon the career he hoped for her after she begins volunteering at a legal practice.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">44</dd>'
					.'<dd class="number season">5</dd>'
					.'<dd class="title">"Pie-O-My"</dd>'
					.'<dd class="director">Henry J. Bronchtein</dd>'
					.'<dd class="writer">Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">October 13, 2002</dd>'
					.'<dt>Ralph invests in a race horse that Tony becomes very attached to. After a choice of self-preservation, Adriana meets her new FBI handler, Agent Sanseverino. Carmela\'s persistence on matters of finance strain her relationship with Tony. Janice strikes up a friendship with Bobby Bacala.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">45</dd>'
					.'<dd class="number season">6</dd>'
					.'<dd class="title">"Everybody Hurts"</dd>'
					.'<dd class="director">Steve Buscemi</dd>'
					.'<dd class="writer">Michael Imperioli</dd>'
					.'<dd class="date">October 20, 2002</dd>'
					.'<dt>Christopher\'s heroin addiction continues to beset his competence. Tony learns of a major development in the life of Gloria Trillo that moves him to a streak of good will. After a situation involving borrowing a large amount of money goes sour, Artie Bucco attempts suicide. A.J. is surprised by his new girlfriend\'s extraordinary wealth.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">46</dd>'
					.'<dd class="number season">7</dd>'
					.'<dd class="title">"Watching Too Much Television"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">Terence Winter, Nick Santora, David Chase, Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">October 27, 2002</dd>'
					.'<dt>After four months of incarceration, Paulie is released, and the family throws him a party at Bada Bing. Tony and Ralph express interest in a plan to scam a government department. Adriana desperately seeks engagement with Christopher, but only so that she could qualify for marital privilege.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">47</dd>'
					.'<dd class="number season">8</dd>'
					.'<dd class="title">"Mergers and Acquisitions"</dd>'
					.'<dd class="director">Dan Attias</dd>'
					.'<dd class="writer">Lawrence Konner, David Chase, Robin Green, Mitchell Burgess, Terence Winter</dd>'
					.'<dd class="date">November 3, 2002</dd>'
					.'<dt>Tony considers starting yet another extramarital relationship, provided he\'s not breaking his own rules. Paulie is concerned with the welfare of his mother after she moves to Green Grove. Furio looks for counsel on how to deal with his feelings for Carmela.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">48</dd>'
					.'<dd class="number season">9</dd>'
					.'<dd class="title">"Whoever Did This"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">November 10, 2002</dd>'
					.'<dt>Uncle Junior falls upon a possible loophole out of his pending trial. Ralph is cast into despair when his son suffers a life-threatening injury. Tony seeks brutal vengeance after a suspicious stable fire. Christopher becomes involved in engineering a disappearance with Tony.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">49</dd>'
					.'<dd class="number season">10</dd>'
					.'<dd class="title">"The Strong, Silent Type"</dd>'
					.'<dd class="director">Alan Taylor</dd>'
					.'<dd class="writer">Terence Winter, Robin Green, Mitchell Burgess, David Chase</dd>'
					.'<dd class="date">November 17, 2002</dd>'
					.'<dt>Tony plans an intervention to confront Christopher and his addiction. Furio tries to distance himself from Carmela. Johnny Sack tries to get in on the HUD scam.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">50</dd>'
					.'<dd class="number season">11</dd>'
					.'<dd class="title">"Calling All Cars"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">David Chase, Robin Green, Mitchell Burgess, David Flebotte, Terence Winter</dd>'
					.'<dd class="date">November 24, 2002</dd>'
					.'<dt>Tony considers reaction as opposed to proaction after he finds out that Carmine Lupertazzi wants a piece of the HUD scam. Uncle Junior\'s shot at avoiding trial is eliminated. Janice tries to steer Bobby Bacala away from the grief that continually plagues him. Dr. Melfi may lose a decidedly memorable patient.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">51</dd>'
					.'<dd class="number season">12</dd>'
					.'<dd class="title">"Eloise"</dd>'
					.'<dd class="director">James Hayman</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">December 1, 2002</dd>'
					.'<dt>Without notice, Furio moves back to Italy, causing anger for Tony, and heartache for Carmela. Carmine\'s restaurant falls victim to vandalism. Meadow\'s annual tea with Carmela becomes confrontational. Paulie and Silvio argue over feelings. Johnny Sack presents a potentially dangerous proposition to Tony.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">52</dd>'
					.'<dd class="number season">13</dd>'
					.'<dd class="title">"Whitecaps"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">Robin Green, Mitchell Burgess, David Chase</dd>'
					.'<dd class="date">December 8, 2002</dd>'
					.'<dt>Junior\'s court case draws to a close. In an attempt to cheer up Carmela, Tony bids on a shore house for the family, but his efforts to save his marriage are swiftly undone. After a change of plans, Christopher is forced to deal with two would-be hitmen. Carmela and Tony finally face off when she finds out he slept with Svetlana.</dt>'
				.'</dl>'
				.'<div style="clear:both;"></div>'
			.'</div>'
		.'</div>'
		.'<div class="sec-container s5">'
			.'<div class="guide">'
				.'<dl class="head">'
					.'<dd class="number">No.</dd>'
					.'<dd class="number season"></dd>'
					.'<dd class="title">Title</dd>'
					.'<dd class="director">Director</dd>'
					.'<dd class="writer">Writer</dd>'
					.'<dd class="date">Air date</dd>'
					.'<dt></dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">53</dd>'
					.'<dd class="number season">1</dd>'
					.'<dd class="title">"Two Tonys"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Terence Winter, David Chase</dd>'
					.'<dd class="date">March 7, 2004</dd>'
					.'<dt>Tony tries to show Dr. Melfi his other side, but is rebuffed; Carmela and A.J. experience wildlife in their yard. Christopher and Paulie have a brief falling out when the "Pine Barrens incident" is re-mentioned. A possible power struggle within the New York Mafia arises.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">54</dd>'
					.'<dd class="number season">2</dd>'
					.'<dd class="title">"Rat Pack"</dd>'
					.'<dd class="director">Alan Taylor</dd>'
					.'<dd class="writer">Matthew Weiner</dd>'
					.'<dd class="date">March 14, 2004</dd>'
					.'<dt>Mafiosi from both the New York and New Jersey crews imprisoned in the 80s are released. Among them is Tony\'s cousin Tony Blundetto; and a reunion party is thrown for them. Further unrest stirs for the New York Mafia after the untimely death of their powerful leader.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">55</dd>'
					.'<dd class="number season">3</dd>'
					.'<dd class="title">"Where\'s Johnny?"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">Michael Caleo</dd>'
					.'<dd class="date">March 21, 2004</dd>'
					.'<dt>An ailing Uncle Junior goes looking for the deceased. Tony\'s powersharing plan for New York does not sit well with Johnny Sack. Paulie and Feech La Manna collide over territory for lawn mowing.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">56</dd>'
					.'<dd class="number season">4</dd>'
					.'<dd class="title">"All Happy Families..."</dd>'
					.'<dd class="director">Rodrigo Garcia</dd>'
					.'<dd class="writer">Toni Kalem</dd>'
					.'<dd class="date">March 28, 2004</dd>'
					.'<dt>A.J. has a night to remember in New York which causes Carmela to temporarily give Tony custody of A.J.; after a series of infractions, Tony handles the Feech La Manna problem. On orders from Johnny Sack, first blood is shed in New York.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">57</dd>'
					.'<dd class="number season">5</dd>'
					.'<dd class="title">"Irregular Around the Margins"</dd>'
					.'<dd class="director">Allen Coulter</dd>'
					.'<dd class="writer">Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">April 4, 2004</dd>'
					.'<dt>While Christopher is away on business, a single-car accident involving Tony and Adriana causes members of the Soprano crew to play a game of telephone. Tensions mount until Tony Blundetto offers a solution that saves face for all involved.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">58</dd>'
					.'<dd class="number season">6</dd>'
					.'<dd class="title">"Sentimental Education"</dd>'
					.'<dd class="director">Peter Bogdanovich</dd>'
					.'<dd class="writer">Matthew Weiner</dd>'
					.'<dd class="date">April 11, 2004</dd>'
					.'<dt>Carmela sets ground rules for A.J.\'s return to her residence while starting a relationship with a school counselor, leading her to face some uncomfortable revelations; Tony Blundetto\'s attempt at going straight goes sour.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">59</dd>'
					.'<dd class="number season">7</dd>'
					.'<dd class="title">"In Camelot"</dd>'
					.'<dd class="director">Steve Buscemi</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">April 18, 2004</dd>'
					.'<dt>Tony meets his late father\'s mistress and learns some troublesome details about his father and a childhood pet; Uncle Junior slips into depression after attending several funerals while under house arrest. Christopher \'helps out\' his AA sponsor, with predictable results.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">60</dd>'
					.'<dd class="number season">8</dd>'
					.'<dd class="title">"Marco Polo"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">Michael Imperioli</dd>'
					.'<dd class="date">April 25, 2004</dd>'
					.'<dt>Carmela throws a 75th birthday party for her father, Hugh, and has a reunion with Tony; as the conflict in New York escalates, Tony Blundetto is courted by an old ally.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">61</dd>'
					.'<dd class="number season">9</dd>'
					.'<dd class="title">"Unidentified Black Males"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Matthew Weiner, Terence Winter</dd>'
					.'<dd class="date">May 2, 2004</dd>'
					.'<dt>Meadow lands her boyfriend a job which later backfires; Tony admits to Dr. Melfi the truth about his cousin\'s arrest. Tony and Carmela receive surprising news.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">62</dd>'
					.'<dd class="number season">10</dd>'
					.'<dd class="title">"Cold Cuts"</dd>'
					.'<dd class="director">Mike Figgis</dd>'
					.'<dd class="writer">Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">May 9, 2004</dd>'
					.'<dt>Janice enters anger management after an incident with another parent at Sophia\'s soccer game; Tony Blundetto and Christopher visit their uncle\'s farm to dig up dead bodies, bringing back unwelcome childhood memories.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">63</dd>'
					.'<dd class="number season">11</dd>'
					.'<dd class="title">"The Test Dream"</dd>'
					.'<dd class="director">Allen Coulter</dd>'
					.'<dd class="writer">David Chase, Matthew Weiner</dd>'
					.'<dd class="date">May 16, 2004</dd>'
					.'<dt>Tony checks into The Plaza Hotel for rest and relaxation but suffers from one of his recurring nightmares. Tony Blundetto takes unauthorized action, threatening to drag Jersey into the New York conflict.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">64</dd>'
					.'<dd class="number season">12</dd>'
					.'<dd class="title">"Long Term Parking"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">May 23, 2004</dd>'
					.'<dt>After she tries to cover up a murder, Adriana is met with increasing demands from the FBI, with tragic consequences. Tony reconciles with Carmela. When calls for an absent Tony Blundetto’s blood are made, Tony makes a final stand for his cousin.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">65</dd>'
					.'<dd class="number season">13</dd>'
					.'<dd class="title">"All Due Respect"</dd>'
					.'<dd class="director">John Patterson</dd>'
					.'<dd class="writer">David Chase, Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">June 6, 2004</dd>'
					.'<dt>With pressure from within and without, Tony is forced to make a difficult decision in order to appease all involved. A.J. develops his business acumen; Carmela counts her blessings. The New York power struggle ends, but a surprise still awaits the victor.</dt>'
				.'</dl>'
				.'<div style="clear:both;"></div>'
			.'</div>'
		.'</div>'
		.'<div class="sec-container s6">'
			.'<div class="guide">'
				.'<dl class="head">'
					.'<dd class="number">No.</dd>'
					.'<dd class="number season"></dd>'
					.'<dd class="title">Title</dd>'
					.'<dd class="director">Director</dd>'
					.'<dd class="writer">Writer</dd>'
					.'<dd class="date">Air date</dd>'
					.'<dt></dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">66</dd>'
					.'<dd class="number season">1</dd>'
					.'<dd class="title">"Members Only"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">March 12, 2006</dd>'
					.'<dt>Eugene Pontecorvo is constrained by obligations when he attempts to retire to Florida. Hesh and his son-in-law become the victims of a brutal assault. The FBI loses an informant within Tony\'s network, and seek to gain a replacement. Uncle Junior\'s increasingly diminished mental state leads to shocking results.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">67</dd>'
					.'<dd class="number season">2</dd>'
					.'<dd class="title">"Join the Club"</dd>'
					.'<dd class="director">David Nutter</dd>'
					.'<dd class="writer">David Chase</dd>'
					.'<dd class="date">March 19, 2006</dd>'
					.'<dt>Tony suffers a loss of identity during a journey through his subconscious. The family has to deal with the situation with him and Junior. A.J. comes through for his family, though he admits to Carmela his complete failure as a college student.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">68</dd>'
					.'<dd class="number season">3</dd>'
					.'<dd class="title">"Mayham"</dd>'
					.'<dd class="director">Jack Bender</dd>'
					.'<dd class="writer">Matthew Weiner</dd>'
					.'<dd class="date">March 26, 2006</dd>'
					.'<dt>Silvio divides the spoils from Paulie\'s latest score and heads off a territorial impasse between Bobby and Vito. Carmela turns to an unexpected source for help with A.J. Christopher revisits his long-lost ambition of breaking into the film business. Tony\'s condition makes a sudden and unexpected change.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">69</dd>'
					.'<dd class="number season">4</dd>'
					.'<dd class="title">"The Fleshy Part of the Thigh"</dd>'
					.'<dd class="director">Alan Taylor</dd>'
					.'<dd class="writer">Diane Frolov, Andrew Schneider</dd>'
					.'<dd class="date">April 2, 2006</dd>'
					.'<dt>Tony and Johnny Sack haggle over the future of Barone Sanitation. Tony finds humor and friendship among fellow hospital patients. Bobby Bacala makes a deal with an aspiring rapper. Paulie is shocked by an aunt\'s revelation; and he later circumvents Tony\'s authority in pursuit of money.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">70</dd>'
					.'<dd class="number season">5</dd>'
					.'<dd class="title">"Mr. & Mrs. John Sacrimoni Request..."</dd>'
					.'<dd class="director">Steve Buscemi</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">April 9, 2006</dd>'
					.'<dt>Johnny Sack files a petition to attend the wedding of his daughter. Tony hires a new driver and bodyguard, Perry Annunziata. Tony resumes his therapy with Dr. Melfi.. At the wedding, Johnny pressures Tony for a favor.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">71</dd>'
					.'<dd class="number season">6</dd>'
					.'<dd class="title">"Live Free or Die"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">David Chase, Terence Winter, Robin Green, Mitchell Burgess</dd>'
					.'<dd class="date">April 16, 2006</dd>'
					.'<dt>Tony debates whether to give a top earner a second chance and looks abroad to settle a local dispute. Christopher makes arrangements to put Tony\'s deal with Johnny Sack into motion. After his sexual orientation becomes common knowledge, an outed Vito flees to New Hampshire to begin a new life.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">72</dd>'
					.'<dd class="number season">7</dd>'
					.'<dd class="title">"Luxury Lounge"</dd>'
					.'<dd class="director">Danny Leiner</dd>'
					.'<dd class="writer">Matthew Weiner</dd>'
					.'<dd class="date">April 23, 2006</dd>'
					.'<dt>Artie\'s business is jeopardized by a rival restaurant and staff scandal provoked by Benny Fazio; Christopher and Little Carmine court Hollywood talent in order to get their film venture off the ground but find themselves out of their depth.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">73</dd>'
					.'<dd class="number season">8</dd>'
					.'<dd class="title">"Johnny Cakes"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Diane Frolov, Andrew Schneider</dd>'
					.'<dd class="date">April 30, 2006</dd>'
					.'<dt>Tony is tempted by a real-estate offer, and the saleswoman who is making the offer. Still in hiding, Vito is wowed by an act of heroism that introduces him to a kindred spirit. A.J. pays a visit to Uncle Junior, with surprising results for both him and his father.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">74</dd>'
					.'<dd class="number season">9</dd>'
					.'<dd class="title">"The Ride"</dd>'
					.'<dd class="director">Alan Taylor</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">May 7, 2006</dd>'
					.'<dt>Christopher makes a surprise announcement regarding his new girlfriend, and falls back into old habits. Paulie pays a price for cutting costs at an Italian Street Fair and learns about a potential illness, leading to a reconciliation. Tony and Chris reminisce over past events after a chance encounter with some thieves.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">75</dd>'
					.'<dd class="number season">10</dd>'
					.'<dd class="title">"Moe n\' Joe"</dd>'
					.'<dd class="director">Steve Shill</dd>'
					.'<dd class="writer">Matthew Weiner</dd>'
					.'<dd class="date">May 14, 2006</dd>'
					.'<dt>Tony leverages Johnny\'s misfortune into a domestic upgrade for his sister; Bacala suffers vision impairment while out on collections. Vito comes clean to Jim about his other life and makes an important decision about his future, as does Johnny Sack.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">76</dd>'
					.'<dd class="number season">11</dd>'
					.'<dd class="title">"Cold Stones"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Diane Frolov, Andrew Schneider, David Chase</dd>'
					.'<dd class="date">May 21, 2006</dd>'
					.'<dt>A frenzy of borrowing money hits the crew; Carmela waxes philosophical on a trip with Rosalie to Paris, leading her to ask some difficult questions about a face from the past; Meadow announces plans to relocate to California. Vito returns to New Jersey.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">77</dd>'
					.'<dd class="number season">12</dd>'
					.'<dd class="title">"Kaisha"</dd>'
					.'<dd class="director">Alan Taylor</dd>'
					.'<dd class="writer">Terence Winter, David Chase, Matthew Weiner</dd>'
					.'<dd class="date">June 4, 2006</dd>'
					.'<dt>Tony helps Carmela get her spec house back on track while Chris picks up where Tony left off. A.J. gets a work perk as he begins a relationship with a colleague and an angered Phil Leotardo will not let well enough alone.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">78</dd>'
					.'<dd class="number season">13</dd>'
					.'<dd class="title">"Soprano Home Movies"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Diane Frolov, Andrew Schneider, David Chase, Matthew Weiner</dd>'
					.'<dd class="date">April 8, 2007</dd>'
					.'<dt>After a close call at home involving a gun charge, Tony and Carmela head to the Adirondacks for a weekend with Bobby and Janice to celebrate Tony\'s birthday. A game of Monopoly turns violent and Bobby does something he thought he would never do. Phil Leotardo returns to his crew.</dt>'
				/*
				.'</dl><dl class="ep">'
					.'<dd class="number">79</dd>'
					.'<dd class="number season">14</dd>'
					.'<dd class="title">"Stage 5"</dd>'
					.'<dd class="director">Alan Taylor</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">April 15, 2007</dd>'
					.'<dt>Art imitates life at the premiere of Christopher\'s horror film Cleaver, leading Tony to evaluate his relationship with his nephew and his own legacy. Johnny Sack absorbs more bad news in prison as Phil analyzes his family history and his future. A dinner between Silvio and Gerry Torciano is rudely interrupted as various figures in New York vie for power.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">80</dd>'
					.'<dd class="number season">15</dd>'
					.'<dd class="title">"Remember When"</dd>'
					.'<dd class="director">Phil Abraham</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">April 22, 2007</dd>'
					.'<dt>Tony and Paulie decide to head south to lie low when the heat turns up in Jersey. Tony grows frustrated with Paulie and begins to question his loyalty and reliability while Junior rediscovers some of his old passion when he sets up a poker game amongst his fellow patients. Phil decides to regain his position of prominence in New York.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">81</dd>'
					.'<dd class="number season">16</dd>'
					.'<dd class="title">"Chasing It"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Matthew Weiner</dd>'
					.'<dd class="date">April 29, 2007</dd>'
					.'<dt>Tony hits an unlucky stretch with a series of gambling losses, creating difficulties between him and Hesh. A.J. makes a life-changing decision regarding his relationship with Blanca, who makes an important decision of her own. Vito\'s widow Marie turns to Tony for help with her troubled son. Carmela makes further progress with her spec house as Phil is inaugurated in New York.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">82</dd>'
					.'<dd class="number season">17</dd>'
					.'<dd class="title">"Walk Like a Man"</dd>'
					.'<dd class="director">Terence Winter</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">May 6, 2007</dd>'
					.'<dt>A.J. struggles with depression. Christopher\'s father-in-law is the unwitting catalyst of a new feud between Christopher and Paulie.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">83</dd>'
					.'<dd class="number season">18</dd>'
					.'<dd class="title">"Kennedy and Heidi"</dd>'
					.'<dd class="director">Alan Taylor</dd>'
					.'<dd class="writer">Matthew Weiner, David Chase</dd>'
					.'<dd class="date">May 13, 2007</dd>'
					.'<dt>An asbestos-disposal impasse raises tensions between Jersey and New York. A car accident leads to tragedy – and Paulie being upstaged. Tony, his family and friends cope with a tragic loss. A.J. reconsiders his friendship with the two Jasons. Tony travels to Las Vegas, where he meets an interesting woman and has a revelation.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">84</dd>'
					.'<dd class="number season">19</dd>'
					.'<dd class="title">"The Second Coming"</dd>'
					.'<dd class="director">Tim Van Patten</dd>'
					.'<dd class="writer">Terence Winter</dd>'
					.'<dd class="date">May 20, 2007</dd>'
					.'<dt>Phil turns down Tony\'s offer of compromise regarding asbestos-disposal. A.J.\'s despair about the world and his future deepens, driving him to the edge. Tony takes umbrage over an affront to Meadow by a member of the Lupertazzi crime family, the consequences of which further widen the rift between Tony and Phil Leotardo.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">85</dd>'
					.'<dd class="number season">20</dd>'
					.'<dd class="title">"The Blue Comet"</dd>'
					.'<dd class="director">Alan Taylor</dd>'
					.'<dd class="writer">David Chase, Matthew Weiner</dd>'
					.'<dd class="date">June 3, 2007</dd>'
					.'<dt>Phil asks some of the members of the New Jersey family to switch sides, testing the allegiance of those closest to Tony. A case of mistaken identity has serious ramifications. The tense situation between the DiMeo and Lupertazzi crime families comes to a head. Dr. Melfi receives some new information and makes a difficult decision.</dt>'
				.'</dl><dl class="ep">'
					.'<dd class="number">86</dd>'
					.'<dd class="number season">21</dd>'
					.'<dd class="title">"Made in America"</dd>'
					.'<dd class="director">David Chase</dd>'
					.'<dd class="writer">David Chase</dd>'
					.'<dd class="date">June 10, 2007</dd>'
					.'<dt>Tony seeks to negotiate a truce with the Lupertazzi family, while at the same time handling his family. Paulie gets a promotion. Meadow and Patrick plan their wedding. A.J. suffers a loss and turns his life in another direction with some help from his parents. Tony comes face-to-face with Uncle Junior. The Soprano family faces the future.</dt>'
				*/
				.'</dl>'
				.'<div style="clear:both;"></div>'
			.'</div>'
		.'</div>'
		.'<img src="img/i27-sopranos-cover-s1.jpg" alt="DVD Cover Season 1" title="DVD Cover Season 1" class="sec-container cover s1" />'
		.'<img src="img/i27-sopranos-cover-s2.jpg" alt="DVD Cover Season 2" title="DVD Cover Season 2" class="sec-container cover s2" />'
		.'<img src="img/i27-sopranos-cover-s3.jpg" alt="DVD Cover Season 3" title="DVD Cover Season 3" class="sec-container cover s3" />'
		.'<img src="img/i27-sopranos-cover-s4.jpg" alt="DVD Cover Season 4" title="DVD Cover Season 4" class="sec-container cover s4" />'
		.'<img src="img/i27-sopranos-cover-s5.jpg" alt="DVD Cover Season 5" title="DVD Cover Season 5" class="sec-container cover s5" />'
		.'<img src="img/i27-sopranos-cover-s6.jpg" alt="DVD Cover Season 6" title="DVD Cover Season 6" class="sec-container cover s6" />'
	.'</div>';
?>
