<?

$_data['issue'] = '27';

$_data['preloadImgs'] = 'img/i27-bg-guide.jpg,img/i27-bg-overlay-guide.png';

$_data['coverDisplay'] = false;

$_data['mainClass'] = 'i27-guide';

$_data['left'] = 'issue27/media2';

$_data['leftHtml'] = '"Media"<strong>Mugshots and more</strong><span>Sopranos Picture Gallery</span>';

$_data['right'] = 'issue27/guide2';

$_data['rightHtml'] = '"Guide"<strong>In all Details</strong><span>Complete Episode Guide</span>';

$_data['main'] =
	'<h3 class="page-title">We break the Omerta</h3>'
	.'<h4 class="page-subtitle">The Seasons\' Plot</h4>'
	.'<div class="sec-containers">'
		.'<h5 class="page-sectitle" data-sec="s1">Season 1</h5>'
		.'<h5 class="page-sectitle" data-sec="s2">Season 2</h5>'
		.'<h5 class="page-sectitle" data-sec="s3">Season 3</h5>'
		.'<div style="clear:both;"></div>'
		.'<h5 class="page-sectitle" data-sec="s4">Season 4</h5>'
		.'<h5 class="page-sectitle" data-sec="s5">Season 5</h5>'
		.'<h5 class="page-sectitle" data-sec="s6">Season 6</h5>'
		.'<div class="sec-container s1">'
			.'<p class="sec">'
				.'The series begins with Tony Soprano collapsing after suffering a panic attack. This prompts him to begin therapy with Dr. Jennifer Melfi. Gradually, the storyline reveals details of Tony\'s upbringing, with his father\'s influence looming large on his development as a gangster, but more so that Tony\'s mother, Livia, was vengeful and possibly personality-disordered. His complicated relationship with his wife Carmela is also explored, as well as her feelings regarding her husband\'s cosa nostra ties. Meadow and Anthony Jr., Tony\'s children gain increasing knowledge of their father\'s mob dealings. Later, federal indictments are brought as a result of someone in his organization talking to the FBI and his own Uncle plots Tony\'s death.'
			.'</p>'
			.'<p class="sec">'
				.'After ordering the execution of Brendan Filone and the mock execution of Chris Moltisanti, Tony\'s Uncle Junior is installed as boss of the family (following the death of previous boss Jackie Aprile, Sr. from cancer), even though Tony actually controls most things from behind the scenes. Furious at Junior\'s plan to have him killed, Tony responds to the attempt on his life with a violent reprisal and confronts his mother for her role in plotting his downfall. She has a psychologically triggered pseudo-stroke and Junior is arrested by the FBI on non-related charges.'
			.'</p>'
		.'</div>'
		.'<div class="sec-container s2">'
			.'<p class="sec">'
				.'At the beginning of the second season, Jackie\'s brother Richie Aprile is released from prison and proves to be uncontrollable in the business arena; he also starts a relationship with Tony\'s sister Janice, who has arrived from Seattle. Tony\'s friend "Big Pussy" returns to New Jersey after a conspicuous absence.'
			.'</p>'
			.'<p class="sec">'
				.'Christopher Moltisanti becomes engaged to his longtime girlfriend Adriana La Cerva. Matthew Bevilaqua and Sean Gismonte, two low-level associates dissatisfied with their perceived lack of success in the Soprano crew, try to make a name for themselves by attempting to kill Christopher. Their plan backfires; Christopher survives the attack (though he is critically wounded), and kills Sean in self-defense, while Tony and Big Pussy murder Matthew soon afterward.'
			.'</p>'
			.'<p class="sec">'
				.'Junior is placed under house arrest as he awaits trial. Richie, frustrated with Tony\'s authority over him, entreats Junior to have Tony killed. Junior feigns interest, then informs Tony of Richie\'s intentions, leaving Tony with another problem to address. However, the situation is defused unexpectedly when Janice kills Richie in a violent argument; Tony and his men conceal all evidence of the murder, and Janice returns to Seattle.'
			.'</p>'
			.'<p class="sec">'
				.'Tony, realizing Big Pussy is an FBI informant, murders him on-board a boat (with assistance from Silvio Dante and Paulie Gualtieri), then wraps his corpse in chains and throws it overboard.'
			.'</p>'
		.'</div>'
		.'<div class="sec-container s3">'
			.'<p class="sec">'
				.'The third season marks the return of the ambitious Ralph Cifaretto following the "disappearance" of Aprile Crew capo Richie Aprile after spending an extended period of leisure time in Miami, Florida. He pursues a relationship with Rosalie Aprile, the widow of the deceased mobster and former capo of the Aprile Crew which bears his name Jackie Aprile, Sr.. With Richie assumed to have joined the witness protection program, Ralph unofficially usurps control over the Aprile Crew, proving to be an exceptionally dexterous earner for the crew. While Ralph\'s competitive merit would seemingly have him next in line to ascend to capo, his insubordination inclines Tony not to promote him and instead gives the promotion to the less qualified – however docile – Gigi Cestone, causing much resentment and tension between him and Ralph.'
			.'</p>'
			.'<p class="sec">'
				.'Jackie Aprile, Jr. becomes involved with Meadow and then descends into an increasingly reckless life of drugs and crime. Tony initially attempts to act as a mentor to Jackie but becomes increasingly impatient with his escalating misbehavior, particularly as Jackie\'s relationship with Meadow begins to become serious. Inspired by a story from Ralph about how Tony, Jackie\'s father, and Silvio Dante got made, Jackie and his friends Dino Zerilli and Carlo Renzi make a similar move and attempt to rob Eugene Pontecorvo\'s Saturday night card game, so they can gain recognition from the family, possibly getting them respected and made as well. The plan takes a turn for the worse when Jackie panics due to the heckling of the card dealer "Sunshine" and shoots him to death. Dino and Carlo are killed during the robbery, but Jackie manages to escape. Tony decides to give Ralph the decision regarding Jackie Jr.\'s punishment. Despite his role as a surrogate father, Ralph ultimately decides to have Jackie Jr. killed.'
			.'</p>'
			.'<p class="sec">'
				.'Ralph ultimately crosses the line when, in a cocaine-induced rage, he gets into a confrontation with one of his girlfriends, Tracee, and beats her to death. She was a \'hooer\', and may have been pregnant with his child at the time. This infuriates Tony to the point where he violates traditional Mafia code by striking him repeatedly in front of the entire family. Bad blood temporarily surfaces between the two but is shortly resolved after Gigi Cestone dies of an aneurysm on the toilet, thereby forcing Tony to reluctantly promote Ralph to capo.'
			.'</p>'
			.'<p class="sec">'
				.'Tony begins an affair with Gloria Trillo, who is also a patient of Dr. Melfi. Their relationship is brief and tumultuous. Meanwhile Dr. Melfi is raped. Junior is diagnosed with stomach cancer; following chemotherapy, it goes into remission. A.J. continues to get in trouble at school, despite success on the football team; this culminates in his expulsion.'
			.'</p>'
		.'</div>'
		.'<div class="sec-container s4">'
			.'<p class="sec">'
				.'In the fourth season, Tony and Christopher stake out the retirement party of Detective Lieutenant Barry Haydu, the man who murdered Christopher\'s father. Tony gives Christopher Haydu\'s address. When Christopher asks why he had been allowed to live all these years, Tony says that he had been valuable, but that he has lived out his worth. Christopher waits inside Haydu\'s home and ambushes him as he returns from his party. Haydu vehemently denies murdering Christopher\'s father, but struggles to get away, yelling "I\'m sorry!" when Christopher goes to shoot him.'
			.'</p>'
			.'<p class="sec">'
				.'New York underboss Johnny Sack becomes enraged after learning Ralph Cifaretto made an inappropriate joke about his wife\'s weight. He seeks permission from boss Carmine Lupertazzi to have Ralph clipped, but is denied. Johnny orders the hit anyway. Tony receives the okay from Carmine to hit Johnny Sack for insubordination. Junior Soprano tips Tony to use an old outfit in Providence for the work. Johnny Sack caves immediately and without explanation, and bloodshed is averted.'
			.'</p>'
			.'<p class="sec">'
				.'Tony and Ralph invest in a race horse named Pie-O-My, who wins several races and makes them both a great deal of money. However, when Ralph\'s 12-year old son Justin is severely injured when an arrow plunges into his chest, Tony comes to believe Ralph burned Pie-O-My in a stable fire to collect $200,000 in insurance money. Tony confronts Ralph the following morning and Ralph denies setting the fire. The two engage in a violent brawl, culminating in Tony strangling Ralph to death. Tony and Christopher dispose of the body; they bury his head and hands at Mikey Palmice\'s father\'s farm and throw his body into a quarry.'
			.'</p>'
			.'<p class="sec">'
				.'While he is leaving court, Uncle Junior is hit in the head with a boom mic and falls down several steps. Tony advises him to take advantage of the opportunity, act mentally incompetent, and employ it as a ruse for not continuing the trial. Later, Eugene Pontecorvo intimidates a juror, resulting in a deadlocked jury, forcing the judge to declare a mistrial.'
			.'</p>'
			.'<p class="sec">'
				.'Following the death of Bobby Baccalieri\'s wife, Janice pursues a romantic relationship with him. Christopher\'s addiction to heroin deepens, prompting his associates and family to organize an intervention, after which he enters a drug rehabilitation center. Adriana befriends a woman who is an undercover FBI agent. When the friendship ends, the woman reveals herself as an FBI agent and tells Adriana the only way to stay out of prison is to become a informant. Adriana agrees and starts sharing information with the FBI.'
			.'</p>'
			.'<p class="sec">'
				.'Carmela, whose relationship with Tony is tense due to financial worries and Tony\'s infidelities, develops a mutual infatuation with Furio Giunta. Furio, incapable of breaking his own moral codes and that of the Sicilian mafia, clandestinely returns home to Italy. After Tony\'s former mistress calls their home, Carmela throws Tony out. Tony is approached by Johnny Sack with a proposal to murder Carmine, which Tony turns down.'
			.'</p>'
		.'</div>'
		.'<div class="sec-container s5">'
			.'<p class="sec">'
				.'In the fifth season, a string of brand new characters are introduced to the show, including Tony\'s cousin Tony Blundetto, who along with other mafiosos are released from prison simultaneously. Among the others released are former DiMeo Crime Family capo Michele "Feech" La Manna, Lupertazzi family capo Phil Leotardo, and semi-retired Lupertazzi consigliere Angelo Garepe. Tony offers Tony B. a job, but he respectfully declines, as he is determined to lead a straight life. He initially begins to take courses to earn a degree in massage therapy and aspires to open up his own massage parlor. After Carmine Lupertazzi dies of a stroke, his death leaves a vacancy for boss of the Lupertazzi Family, which will soon be fought over by underboss Johnny Sack and Carmine\'s son Carmine Lupertazzi, Jr.. After Feech proves to be an insubordinate presence, Tony arranges for him to be sent back to prison by setting him up with stolen property, violating his parole.'
			.'</p>'
			.'<p class="sec">'
				.'The war between Johnny Sack and Carmine, Jr. begins when Johnny has Phil kill lady shylock Lorraine Calluzzo. Tony B.\'s attempt to stay straight comes to a head when he gets into a brawl with his employer Sungyon Kim. Tony informs Tony B. that "it\'s hard working with strangers." Angelo, who was a good friend to Tony B. in prison, and Lupertazzi capo Rusty Millio offer Tony B. the job of taking out Joey Peeps in retaliation for Lorraine\'s death. Tony B. initially declines but, desperate to earn, accepts the job. He catches Joey outside a bordello, shoots him, and quickly flees the scene. Johnny believes Tony B. is involved, and retaliates by having Phil and his brother Billy Leotardo kill Angelo. Tony B. finds the Leotardo brothers and opens fire, killing Billy and wounding Phil.'
			.'</p>'
			.'<p class="sec">'
				.'Still separated from Carmela, Tony is living at his parents\' house. Carmela, now the sole authority figure in the home, becomes frustrated as her rules lead A.J. to resent her; eventually she allows him to live with his father. She has a brief relationship with Robert Wegler, A.J.\'s guidance counselor; he breaks it off abruptly when he suspects that she is manipulating him to improve A.J.\'s grades. Tony and Carmela reconcile; Tony promises to be more loyal and agrees to pay for a piece of real estate Carmela wishes to develop.'
			.'</p>'
			.'<p class="sec">'
				.'Tony gets Meadow\'s boyfriend Finn De Trolio a summer job at a construction site, which is run by Aprile Crew capo Vito Spatafore. Finn comes in early one morning and catches Vito performing oral sex on a security guard. Vito tries to buddy up to Finn so that he does not say anything to anybody else. He even asks Finn to a Yankees game, which Finn does not attend. Finn soon quits the job out of fear.'
			.'</p>'
			.'<p class="sec">'
				.'After covering up a murder that occurred at The Crazy Horse, Adriana is arrested and pressured by the F.B.I. to wear a wire to avoid being charged as an accomplice. She refuses to wear a wire and informs the F.B.I. that she may be able to persuade her fiancé Christopher to co-operate and become an informant against Tony. She confesses to Christopher that she has been informing and that the F.B.I. would give them new identities if they would testify. Christopher is grief-stricken and nearly kills her. He leaves the apartment, saying he needs time to think. Tony has Silvio pick up Adriana under the pretense of taking her to see Christopher, but instead drives her out to the woods and executes her. Adriana’s betrayal and subsequent execution is too much for Christopher to handle and he briefly returns to drug abuse to deal with the pain.'
			.'</p>'
			.'<p class="sec">'
				.'Phil Leotardo and his henchmen beat Benny Fazio while trying to acquire the whereabouts of Tony B.; Phil also threatens to have Christopher taken out if Tony B.\'s whereabouts are not disclosed soon. To avoid any more of his guys getting hurt and to pacify New York, Tony tracks Tony B. to their Uncle Pat\'s farm and shoots him. Phil, however, is furious that he did not get the opportunity to do it himself. Tony and Johnny meet at Johnny\'s house in a reconciliatory manner, but Johnny is arrested by Federal agents, while Tony escapes.'
			.'</p>'
		.'</div>'
		.'<div class="sec-container s6">'
			.'<p class="sec">'
				.'At the beginning of the sixth season, Tony is shot by the now senile and confused Uncle Junior. Rendered comatose, Tony dreams he is a salesman on a business trip, where he mistakenly exchanges his briefcase and identification with a man named Kevin Finnerty. Tony\'s recovery from the shooting changes his outlook, and he tries to mend his ways. However, he is faced with more problems in his business life.'
			.'</p>'
			.'<p class="sec">'
				.'Once out of the hospital, Johnny Sack\'s daughter gets married and the Soprano family attends. Once there Tony is shown very exhausted and through security must take off his shoes. In the process he collapses to the ground, but is not hurt. Before the wedding Johnny Sack is approved to leave prison for six hours to see his daughter get married and that he has to pay for the metal detectors and the presence of the U.S. marshals at the event. As his daughter is about to drive away the SUV that was escorting Johnny to the wedding blocks the car from leaving and an altercation begins in the driveway. In a moment of weakness and despair Johnny Sack cries as he is put back into handcuffs and driven back to prison, greatly diminishing the respect his crew and Tony\'s crew have for him.'
			.'</p>'
			.'<p class="sec">'
				.'Vito Spatafore is outed as a homosexual after running into a friend at a New York night club. The rumor spreads quickly, and once word gets to Meadow that everyone else knows, she tells Tony and Carmela about the incident between Finn and Vito with the security guard. Finn then has to sit in front of Tony\'s entire crew and tell them what happened with the guard, solidifying their thoughts on Vito\'s sexuality. Tony is urged to deal with the problem by Phil Leotardo, now acting boss of New York with Johnny Sack in prison. Once Vito is outed, he runs away from the city and hides out in a New Hampshire town where he starts writing a book and meets with the locals. Vito also starts a romantic relationship with a male cook at a local diner. Eventually, Vito returns to New Jersey and asks Tony to allow him to return to work, albeit in Atlantic City. He continues to maintain that he is not a homosexual. Tony mulls over the decision to let him work, as well as whether to let him live. When Tony fails to act, Phil intervenes and kills Spatafore. When one of the members of the New York family, Fat Dom Gamiello, pays a visit to the Jersey office and won\'t stop making jokes about Vito and his death, the two members of Tony\'s crime family who are present kill Fat Dom out of anger at the disrespect he has shown. Once more, it appears that the families are on the verge of all-out war.'
			.'</p>'
			.'<p class="sec">'
				.'Also during the first half of the season Chris and Carmine head to Los Angeles to try to pick up Ben Kingsley for a movie they are trying to make called "Cleaver." Basically a mix of "The Godfather" and "Saw." But Ben passes on the picture. While in Los Angeles Chris goes back to using cocaine for a short period of time.'
			.'</p>'
			.'<p class="sec">'
				.'Tony considers killing several of his associates for relatively minor infractions. Christopher is unable to leave the mob, deflecting his problems by relapsing into drug addiction and kills his friend from Narcotics Anonymous. He is then seriously injured in a car accident that he causes while driving under the influence of narcotics. Tony, the sole passenger, is not badly hurt, and suffocates Christopher to death. A.J. is dumped by his fiancée and slips into depression, culminating in a failed suicide attempt in the backyard pool. Dr. Melfi is convinced by friends that Tony is making no progress and may even be using talking therapy for his own sociopathic benefit. She drops him as a patient.'
			.'</p>'
			.'<p class="sec">'
				.'Johnny Sack dies from lung cancer while imprisoned, and Leotardo then consolidates his position in the Lupertazzi family by having his rivals for the leadership killed. Phil then officially takes over, igniting a resumption of the past feud with Tony and refusing to compromise with Tony on a garbage deal. When Tony assaults a Lupertazzi soldier for harassing Meadow while she is on a date, Phil decides it\'s time to decapitate the Soprano crew. He orders the executions of Bobby Baccalieri, who is shot to death; Silvio, who ends up comatose; and Tony, who goes into hiding. A deal is brokered whereby the rest of the Lupertazzi family agrees to ignore the order to kill Tony, giving Tony an opportunity to go after Phil. An FBI agent informs Tony of Phil\'s location, allowing Tony to have him killed. Tony suspects that Carlo, a capo from New Jersey, has become an informant in an attempt to help out his son, who has recently been caught for dealing ecstasy. Tony meets with his lawyer, who informs him that subpoenas are being given to New Jersey and New York crews alike. Sometime after Phil\'s death and a meeting with everyone, Tony, Carmela, and AJ meet for a casual dinner, while the Journey song "Don\'t Stop Believin\'" plays in the background. At this time, several individuals become apparent that seem out of place for the venue. Meadow is shown coming to the dinner late and crossing the street as the rest of the family starts to eat an appetizer. Three individuals that appeared as hit-men in an earlier episode enter and are specifically focused upon during entry. As Meadow walks up to the door, the screen goes to Tony. Immediately, an individual that had been previously shown at the counter specifically taking notice of Tony, is shown entering the restroom, the door of which is directly facing, (and approximately 90 degrees to), the Table at which Tony and his family are sitting. The diner door opens with a bell ringing, Tony looks up and the show smash cuts to black and the credits roll in silence, leaving his and his family\'s fate a mystery.'
			.'</p>'
		.'</div>'
		.'<img src="img/i27-sopranos-cover-s1.jpg" alt="DVD Cover Season 1" title="DVD Cover Season 1" class="sec-container cover s1" />'
		.'<img src="img/i27-sopranos-cover-s2.jpg" alt="DVD Cover Season 2" title="DVD Cover Season 2" class="sec-container cover s2" />'
		.'<img src="img/i27-sopranos-cover-s3.jpg" alt="DVD Cover Season 3" title="DVD Cover Season 3" class="sec-container cover s3" />'
		.'<img src="img/i27-sopranos-cover-s4.jpg" alt="DVD Cover Season 4" title="DVD Cover Season 4" class="sec-container cover s4" />'
		.'<img src="img/i27-sopranos-cover-s5.jpg" alt="DVD Cover Season 5" title="DVD Cover Season 5" class="sec-container cover s5" />'
		.'<img src="img/i27-sopranos-cover-s6.jpg" alt="DVD Cover Season 6" title="DVD Cover Season 6" class="sec-container cover s6" />'
	.'</div>';

?>
