<?

$_data['menu'] = '<menu id="main-menu">'
	.'<li class="item">'
		.'<a rel="request" href="issue27" class="cover">Cover</a>'
		.'<div class="sub cover"><a rel="request" href="issue27"></a></div>'
	.'</li>'
	.'<li class="item">'
		.'<a rel="request" href="issue27/guide">Guide</a>'
		.'<ul class="sub">'
			.'<li>'
				.'<a rel="request" href="issue27/guide">'
					.'We break the Omerta'
					.'<span>Seasons\' Plot</span>'
				.'</a>'
			.'</li>'
			.'<li>'
				.'<a rel="request" href="issue27/guide2">'
					.'in all details'
					.'<span>Episode Guide</span>'
				.'</a>'
			.'</li>'
		.'</ul>'
	.'</li>'
	.'<li class="item">'
		.'<a rel="request" href="issue27/cast">Cast</a>'
		.'<ul class="sub" style="left:-90px">'
			.'<li>'
				.'<a rel="request" href="issue27/cast">'
					.'Friends of mine, friends of ours and civilians'
					.'<span>Introducing the Crew</span>'
				.'</a>'
			.'</li>'
			.'<li>'
				.'<a rel="request" href="issue27/cast2">'
					.'Sleeping with the Fishes'
					.'<span>See who\'s gone forever and why</span>'
				.'</a>'
			.'</li>'
		.'</ul>'
	.'</li>'
	.'<li class="item">'
		.'<a rel="request" href="issue27/interview">Interview</a>'
		.'<ul class="sub" style="left:-30px">'
			.'<li>'
				.'<a rel="request" href="issue27/interview">'
					.'Meet New Jersey\'s Garbage King'
					.'<span>Interview with James Gandolfini</span>'
				.'</a>'
			.'</li>'
			.'<li>'
				.'<a rel="request" href="issue27/interview2">'
					.'Capo di tutti capi'
					.'<span>Interview with creator David Chase</span>'
				.'</a>'
			.'</li>'
		.'</ul>'
	.'</li>'
	.'<li class="item">'
		.'<a rel="request" href="issue27/trivia">Trivia</a>'
		.'<ul class="sub" style="left:-54px">'
			.'<li>'
				.'<a rel="request" href="issue27/trivia">'
					.'They pull you back in'
					.'<span>Best quotes and scenes</span>'
				.'</a>'
			.'</li>'
		.'</ul>'
	.'</li>'
	.'<li class="item">'
		.'<a rel="request" href="issue27/media">media</a>'
		.'<ul class="sub" style="left:-124px">'
			.'<li>'
				.'<a rel="request" href="issue27/media">'
					.'Uncut Family Business'
					.'<span>Sopranos Video Clips</span>'
				.'</a>'
			.'</li>'
			.'<li>'
				.'<a rel="request" href="issue27/media2">'
					.'Mugshots and more'
					.'<span>Sopranos Picture Gallery</span>'
				.'</a>'
			.'</li>'
		.'</ul>'
	.'</li>'
	.'</menu>';

?>
